console.log("my first console project");
var first_name ="neelayyagari";
var middle_name ="haasika";
var last_name ="naidu";
console.log(first_name);
console.log(middle_name);
console.log(last_name);
var fm_name =first_name.concat(middle_name);
console.log(fm_name);
var full_name =fm_name.concat(last_name) ;
console.log(full_name);
var brother_name = full_name.replace("haasika","kovid");
console.log(brother_name);
var caps_full_name =full_name.toUpperCase();
console.log(caps_full_name);
var a =10;
var b =5;
var maths_num =Math.max(a,b);
console.log(maths_num);